# Generated by Django 6.1.1 on 2026-09-10 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_rapprochement_resultatrapprochement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transid_mvola', models.CharField(db_index=True, max_length=50)),
                ('type_ecart', models.CharField(choices=[('ORPHELINE_MVOLA', 'Orpheline MVOLA'), ('ORPHELINE_PAMF', 'Orpheline PAMF')], max_length=20)),
                ('date_transaction', models.DateField()),
                ('statut', models.CharField(choices=[('DETECTE', 'Detecte'), ('EN_COURS', 'En cours de traitement'), ('REGULARISE', 'Regularise')], default='DETECTE', max_length=15)),
                ('detecte_le', models.DateTimeField(auto_now_add=True)),
                ('resultat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecart', to='transactions.resultatrapprochement')),
            ],
            options={
                'ordering': ['-detecte_le'],
            },
        ),
    ]
