# Generated by Django 6.1.1 on 2026-09-10 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcartHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('COMMENTAIRE', 'Commentaire'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('PIECE_JOINTE', 'Piece jointe')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=15)),
                ('nouveau_statut', models.CharField(blank=True, max_length=15)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ecarts/pieces_jointes/%Y/%m/')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_ecarts', to=settings.AUTH_USER_MODEL)),
                ('ecart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='ecarts.ecart')),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
    ]
