# Generated by Django 6.1.1 on 2026-09-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarts', '0002_ecarthistorique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecarthistorique',
            name='reference_externe',
            field=models.CharField(blank=True, help_text='Reference du ticket Aspekt, ou reference/commentaire de la confirmation de rollback.', max_length=100),
        ),
        migrations.AlterField(
            model_name='ecarthistorique',
            name='action',
            field=models.CharField(choices=[('COMMENTAIRE', 'Commentaire'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('PIECE_JOINTE', 'Piece jointe'), ('TICKET_ASPEKT', 'Ticket Aspekt enregistre'), ('ROLLBACK_CONFIRME', 'Rollback MVOLA confirme')], max_length=20),
        ),
    ]
