# Generated by Django 5.2.17 on 2026-09-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarts', '0003_ecarthistorique_reference_externe_and_more'),
        ('transactions', '0005_importfichierom_importrequeteom_rapprochementom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcartOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transid_om', models.CharField(db_index=True, max_length=50)),
                ('type_ecart', models.CharField(choices=[('ORPHELINE_OM', 'Orpheline Orange Money'), ('ORPHELINE_PAMF', 'Orpheline PAMF')], max_length=20)),
                ('date_transaction', models.DateField()),
                ('statut', models.CharField(choices=[('DETECTE', 'Detecte'), ('EN_COURS', 'En cours de traitement'), ('REGULARISE', 'Regularise')], default='DETECTE', max_length=15)),
                ('detecte_le', models.DateTimeField(auto_now_add=True)),
                ('resultat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecart', to='transactions.resultatrapprochementom')),
            ],
            options={
                'ordering': ['-detecte_le'],
            },
        ),
        migrations.CreateModel(
            name='EcartHistoriqueOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('COMMENTAIRE', 'Commentaire'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('PIECE_JOINTE', 'Piece jointe'), ('TICKET_ASPEKT', 'Ticket Aspekt enregistre'), ('ROLLBACK_CONFIRME', 'Rollback Orange Money confirme')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('ancien_statut', models.CharField(blank=True, max_length=15)),
                ('nouveau_statut', models.CharField(blank=True, max_length=15)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ecarts/pieces_jointes_om/%Y/%m/')),
                ('reference_externe', models.CharField(blank=True, help_text='Reference du ticket Aspekt, ou reference/commentaire de la confirmation de rollback.', max_length=100)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_ecarts_om', to=settings.AUTH_USER_MODEL)),
                ('ecart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='ecarts.ecartom')),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
    ]
