# Generated by Django 5.2.17 on 2026-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarts', '0004_ecartom_ecarthistoriqueom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecart',
            name='type_ecart',
            field=models.CharField(choices=[('ORPHELINE_MVOLA', 'Orpheline MVOLA'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ecarthistorique',
            name='action',
            field=models.CharField(choices=[('COMMENTAIRE', 'Commentaire'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('PIECE_JOINTE', 'Piece jointe'), ('TICKET_ASPEKT', 'Ticket Aspekt enregistre'), ('ROLLBACK_CONFIRME', 'Rollback MVOLA confirme'), ('RESOLUTION_DOUBLON', 'Doublon PAMF resolu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ecarthistoriqueom',
            name='action',
            field=models.CharField(choices=[('COMMENTAIRE', 'Commentaire'), ('CHANGEMENT_STATUT', 'Changement de statut'), ('PIECE_JOINTE', 'Piece jointe'), ('TICKET_ASPEKT', 'Ticket Aspekt enregistre'), ('ROLLBACK_CONFIRME', 'Rollback Orange Money confirme'), ('RESOLUTION_DOUBLON', 'Doublon PAMF resolu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ecartom',
            name='type_ecart',
            field=models.CharField(choices=[('ORPHELINE_OM', 'Orpheline Orange Money'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)')], max_length=20),
        ),
    ]
