# Generated by Django 5.2.17 on 2026-09-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecarts', '0005_alter_ecart_type_ecart_alter_ecarthistorique_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecart',
            name='type_ecart',
            field=models.CharField(choices=[('ORPHELINE_MVOLA', 'Orpheline MVOLA'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)'), ('TRANSACTION_REJOUEE', 'Transaction rejouee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ecartom',
            name='type_ecart',
            field=models.CharField(choices=[('ORPHELINE_OM', 'Orpheline Orange Money'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)'), ('TRANSACTION_REJOUEE', 'Transaction rejouee')], max_length=20),
        ),
    ]
