# Generated by Django 6.1.1 on 2026-09-10 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFichierMvola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/mvola/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('date_fichier', models.DateField(verbose_name='date du fichier')),
                ('importe_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succes'), ('ECHEC', 'Echec')], max_length=10)),
                ('nb_lignes_lues', models.PositiveIntegerField(default=0)),
                ('nb_lignes_inserees', models.PositiveIntegerField(default=0)),
                ('nb_doublons', models.PositiveIntegerField(default=0)),
                ('nb_erreurs', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_mvola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importe_le'],
            },
        ),
        migrations.CreateModel(
            name='ImportRequetePamf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requete', models.DateField(verbose_name='date interrogee (postingDate)')),
                ('executee_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succes'), ('ECHEC', 'Echec')], max_length=10)),
                ('nb_lignes', models.PositiveIntegerField(default=0)),
                ('nb_doublons', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('executee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_pamf', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executee_le'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMvola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_trans', models.DateTimeField()),
                ('transid_mvola', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='TRANSID_MVOLA')),
                ('state', models.CharField(max_length=30)),
                ('msisdn', models.CharField(max_length=20)),
                ('pivot', models.CharField(max_length=30)),
                ('sens', models.CharField(max_length=5)),
                ('nom', models.CharField(max_length=150)),
                ('transid_parent', models.CharField(blank=True, default='0', max_length=50)),
                ('trans_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('solde_pivot_avant', models.DecimalField(decimal_places=2, max_digits=18)),
                ('solde_pivot_apres', models.DecimalField(decimal_places=2, max_digits=18)),
                ('origftid', models.CharField(blank=True, max_length=50)),
                ('type_operation', models.CharField(max_length=10)),
                ('import_fichier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.importfichiermvola')),
            ],
            options={
                'ordering': ['-date_trans'],
                'indexes': [models.Index(fields=['date_trans'], name='transaction_date_tr_92dac6_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionPamf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_autotransaction_id', models.CharField(max_length=50, verbose_name='rAutotransactionID')),
                ('posting_date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('transid_mvola', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='TRANSID_MVOLA')),
                ('response_body', models.TextField(blank=True)),
                ('import_requete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.importrequetepamf')),
            ],
            options={
                'ordering': ['-posting_date'],
                'indexes': [models.Index(fields=['posting_date'], name='transaction_posting_81fcee_idx')],
            },
        ),
    ]
