# Generated by Django 6.1.1 on 2026-09-10 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapprochement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('ECHEC', 'Echec')], default='EN_COURS', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('execute_le', models.DateTimeField(auto_now=True)),
                ('nb_mvola', models.PositiveIntegerField(default=0)),
                ('nb_pamf', models.PositiveIntegerField(default=0)),
                ('nb_success', models.PositiveIntegerField(default=0)),
                ('nb_orphelines_mvola', models.PositiveIntegerField(default=0)),
                ('nb_orphelines_pamf', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('lance_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapprochements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ResultatRapprochement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transid_mvola', models.CharField(db_index=True, max_length=50)),
                ('statut', models.CharField(choices=[('SUCCESS', 'Rapprochee'), ('ORPHELINE_MVOLA', 'Orpheline MVOLA'), ('ORPHELINE_PAMF', 'Orpheline PAMF')], max_length=20)),
                ('rapprochement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='transactions.rapprochement')),
                ('transaction_mvola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='transactions.transactionmvola')),
                ('transaction_pamf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='transactions.transactionpamf')),
            ],
            options={
                'indexes': [models.Index(fields=['statut'], name='transaction_statut_6685c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('rapprochement', 'transid_mvola'), name='unique_resultat_par_transid')],
            },
        ),
    ]
