# Generated by Django 6.1.1 on 2026-09-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rapprochement_resultatrapprochement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultatrapprochement',
            options={'ordering': ['transid_mvola']},
        ),
    ]
