# Generated by Django 6.1.1 on 2026-09-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_resultatrapprochement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpamf',
            name='is_success',
            field=models.BooleanField(default=True, help_text='Status CBS = 3 (poste/valide). False = transaction presente mais en echec cote PAMF.', verbose_name='is_sucess'),
        ),
    ]
