# Generated by Django 5.2.17 on 2026-09-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactionpamf_is_success'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFichierOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='imports/om/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('date_fichier', models.DateField(verbose_name='date du fichier')),
                ('importe_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succes'), ('ECHEC', 'Echec')], max_length=10)),
                ('nb_lignes_lues', models.PositiveIntegerField(default=0)),
                ('nb_lignes_inserees', models.PositiveIntegerField(default=0)),
                ('nb_doublons', models.PositiveIntegerField(default=0)),
                ('nb_hors_succes', models.PositiveIntegerField(default=0, help_text='Lignes ignorees car Statut != Succes (cf. CLAUDE.md).')),
                ('nb_erreurs', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('importe_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_om', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-importe_le'],
            },
        ),
        migrations.CreateModel(
            name='ImportRequeteOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requete', models.DateField(verbose_name='date interrogee (postingDate)')),
                ('executee_le', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('SUCCES', 'Succes'), ('ECHEC', 'Echec')], max_length=10)),
                ('nb_lignes', models.PositiveIntegerField(default=0)),
                ('nb_doublons', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('executee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports_pamf_om', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-executee_le'],
            },
        ),
        migrations.CreateModel(
            name='RapprochementOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('ECHEC', 'Echec')], default='EN_COURS', max_length=10)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('execute_le', models.DateTimeField(auto_now=True)),
                ('nb_om', models.PositiveIntegerField(default=0)),
                ('nb_pamf', models.PositiveIntegerField(default=0)),
                ('nb_success', models.PositiveIntegerField(default=0)),
                ('nb_orphelines_om', models.PositiveIntegerField(default=0)),
                ('nb_orphelines_pamf', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True)),
                ('lance_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapprochements_om', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ligne', models.PositiveIntegerField(verbose_name='N (relevé OM)')),
                ('date_trans', models.DateTimeField()),
                ('transid_om', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='TRANSID_ORANGE_MONEY')),
                ('service', models.CharField(blank=True, max_length=50)),
                ('paiement', models.CharField(blank=True, max_length=50)),
                ('statut', models.CharField(max_length=20)),
                ('mode', models.CharField(blank=True, max_length=30)),
                ('compte_technique', models.CharField(blank=True, max_length=30)),
                ('wallet_agent', models.CharField(blank=True, max_length=30)),
                ('pseudo', models.CharField(blank=True, max_length=50)),
                ('msisdn', models.CharField(max_length=20)),
                ('wallet_correspondant', models.CharField(blank=True, max_length=30)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Colonne Credit (MGA).', max_digits=18)),
                ('commissions', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('import_fichier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.importfichierom')),
            ],
            options={
                'ordering': ['-date_trans'],
            },
        ),
        migrations.CreateModel(
            name='TransactionPamfOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_autotransaction_id', models.CharField(max_length=50, verbose_name='rAutotransactionID')),
                ('posting_date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('transid_om', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='TRANSID_ORANGE_MONEY')),
                ('response_body', models.TextField(blank=True)),
                ('is_success', models.BooleanField(default=True, help_text='Status CBS = 3 (poste/valide). False = transaction presente mais en echec cote PAMF.', verbose_name='is_sucess')),
                ('import_requete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.importrequeteom')),
            ],
            options={
                'ordering': ['-posting_date'],
            },
        ),
        migrations.CreateModel(
            name='ResultatRapprochementOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transid_om', models.CharField(db_index=True, max_length=50)),
                ('statut', models.CharField(choices=[('SUCCESS', 'Rapprochee'), ('ORPHELINE_OM', 'Orpheline Orange Money'), ('ORPHELINE_PAMF', 'Orpheline PAMF')], max_length=20)),
                ('rapprochement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='transactions.rapprochementom')),
                ('transaction_om', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='transactions.transactionom')),
                ('transaction_pamf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='transactions.transactionpamfom')),
            ],
            options={
                'ordering': ['transid_om'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionom',
            index=models.Index(fields=['date_trans'], name='transaction_date_tr_d17f92_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionpamfom',
            index=models.Index(fields=['posting_date'], name='transaction_posting_95ce95_idx'),
        ),
        migrations.AddIndex(
            model_name='resultatrapprochementom',
            index=models.Index(fields=['statut'], name='transaction_statut_f8a339_idx'),
        ),
        migrations.AddConstraint(
            model_name='resultatrapprochementom',
            constraint=models.UniqueConstraint(fields=('rapprochement', 'transid_om'), name='unique_resultat_om_par_transid'),
        ),
    ]
