# Generated by Django 5.2.17 on 2026-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_importfichierom_importrequeteom_rapprochementom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpamfom',
            name='transid_om',
            field=models.CharField(db_index=True, max_length=50, verbose_name='TRANSID_ORANGE_MONEY'),
        ),
        migrations.AddConstraint(
            model_name='transactionpamfom',
            constraint=models.UniqueConstraint(fields=('transid_om', 'r_autotransaction_id'), name='unique_pamfom_transid_rautotransactionid'),
        ),
    ]
