# Generated by Django 5.2.17 on 2026-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transactionpamfom_transid_om_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapprochement',
            name='nb_doublons_pamf',
            field=models.PositiveIntegerField(default=0, help_text='Transactions avec plusieurs postings PAMF, a resoudre manuellement.'),
        ),
        migrations.AddField(
            model_name='rapprochementom',
            name='nb_doublons_pamf',
            field=models.PositiveIntegerField(default=0, help_text='Transactions avec plusieurs postings PAMF, a resoudre manuellement.'),
        ),
        migrations.AlterField(
            model_name='resultatrapprochement',
            name='statut',
            field=models.CharField(choices=[('SUCCESS', 'Rapprochee'), ('ORPHELINE_MVOLA', 'Orpheline MVOLA'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resultatrapprochementom',
            name='statut',
            field=models.CharField(choices=[('SUCCESS', 'Rapprochee'), ('ORPHELINE_OM', 'Orpheline Orange Money'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionpamf',
            name='transid_mvola',
            field=models.CharField(db_index=True, max_length=50, verbose_name='TRANSID_MVOLA'),
        ),
        migrations.AddConstraint(
            model_name='transactionpamf',
            constraint=models.UniqueConstraint(fields=('transid_mvola', 'r_autotransaction_id'), name='unique_pamf_transid_rautotransactionid'),
        ),
    ]
