# Generated by Django 5.2.17 on 2026-09-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_rapprochement_nb_doublons_pamf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpamfom',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant CBS (AmountCRY), somme des postings pour un remboursement scinde (apiServiceId=303).', max_digits=18, null=True),
        ),
    ]
