# Generated by Django 5.2.17 on 2026-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactionpamfom_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapprochement',
            name='nb_transactions_rejouees',
            field=models.PositiveIntegerField(default=0, help_text="Orphelines PAMF qui correspondent a une orpheline MVOLA d'une date anterieure."),
        ),
        migrations.AddField(
            model_name='rapprochementom',
            name='nb_transactions_rejouees',
            field=models.PositiveIntegerField(default=0, help_text="Orphelines PAMF qui correspondent a une orpheline OM d'une date anterieure."),
        ),
        migrations.AlterField(
            model_name='resultatrapprochement',
            name='statut',
            field=models.CharField(choices=[('SUCCESS', 'Rapprochee'), ('ORPHELINE_MVOLA', 'Orpheline MVOLA'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)'), ('TRANSACTION_REJOUEE', 'Transaction rejouee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resultatrapprochementom',
            name='statut',
            field=models.CharField(choices=[('SUCCESS', 'Rapprochee'), ('ORPHELINE_OM', 'Orpheline Orange Money'), ('ORPHELINE_PAMF', 'Orpheline PAMF'), ('DOUBLON_PAMF', 'Doublon PAMF (postings multiples)'), ('TRANSACTION_REJOUEE', 'Transaction rejouee')], max_length=20),
        ),
    ]
