# Generated by Django 5.2.17 on 2026-09-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_add_transaction_rejouee_status_and_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionpamf',
            name='apiservice',
            field=models.IntegerField(blank=True, help_text='apiServiceId from apiLog', null=True),
        ),
        migrations.AddField(
            model_name='transactionpamf',
            name='body',
            field=models.TextField(blank=True, help_text='requestBody from apiLog'),
        ),
        migrations.AddField(
            model_name='transactionpamf',
            name='path',
            field=models.TextField(blank=True, help_text='RequestURL from apiLog'),
        ),
        migrations.AddField(
            model_name='transactionpamfom',
            name='apiservice',
            field=models.IntegerField(blank=True, help_text='apiServiceId from apiLog', null=True),
        ),
        migrations.AddField(
            model_name='transactionpamfom',
            name='body',
            field=models.TextField(blank=True, help_text='requestBody from apiLog'),
        ),
        migrations.AddField(
            model_name='transactionpamfom',
            name='path',
            field=models.TextField(blank=True, help_text='RequestURL from apiLog'),
        ),
    ]
