# Generated by Django 6.1.1 on 2026-09-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('importer_csv_mvola', 'Importer un fichier CSV MVOLA'), ('lancer_rapprochement', 'Lancer un rapprochement'), ('traiter_ecarts', 'Traiter les ecarts (statut, commentaire, piece jointe, rollback, ticket Aspekt)'), ('gerer_roles', 'Gerer les roles et privileges'), ('gerer_utilisateurs', 'Gerer les utilisateurs (assignation de roles)')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='user.permission', verbose_name='privileges')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='user.role', verbose_name='roles'),
        ),
    ]
